// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutPageDocumentDataSlicesSlice =
  | CtaSectionSlice
  | AboutSectionSlice
  | HeroSectionSlice;

/**
 * Content for About Page documents
 */
interface AboutPageDocumentData {
  /**
   * Slice Zone field in *About Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutPageDocumentDataSlicesSlice> /**
   * Meta Title field in *About Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *About Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * About Page document from Prismic
 *
 * - **API ID**: `about_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AboutPageDocumentData>,
    "about_page",
    Lang
  >;

type BlogPostDocumentDataSlicesSlice =
  | BlogDetailsSectionSlice
  | HeroSectionSlice
  | CtaSectionSlice;

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
  /**
   * Heading field in *Blog Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *Blog Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Published Date field in *Blog Post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.published_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  published_date: prismic.DateField;

  /**
   * Slice Zone field in *Blog Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice> /**
   * Meta Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Featured Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.featured_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<"large" | "medium" | "thumbnail">;
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    "blog_post",
    Lang
  >;

type BlogsPageDocumentDataSlicesSlice = BlogsSectionSlice | HeroSectionSlice;

/**
 * Content for Blogs Page documents
 */
interface BlogsPageDocumentData {
  /**
   * Slice Zone field in *Blogs Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blogs_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogsPageDocumentDataSlicesSlice> /**
   * Meta Title field in *Blogs Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blogs_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blogs Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blogs_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blogs Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogs_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Blogs Page document from Prismic
 *
 * - **API ID**: `blogs_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogsPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<BlogsPageDocumentData>,
    "blogs_page",
    Lang
  >;

type CategoriesPageDocumentDataSlicesSlice =
  | HeroSectionSlice
  | CategoriesSectionSlice;

/**
 * Content for Categories Page documents
 */
interface CategoriesPageDocumentData {
  /**
   * Slice Zone field in *Categories Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: categories_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CategoriesPageDocumentDataSlicesSlice> /**
   * Meta Title field in *Categories Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: categories_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Categories Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: categories_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Categories Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: categories_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Categories Page document from Prismic
 *
 * - **API ID**: `categories_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategoriesPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CategoriesPageDocumentData>,
    "categories_page",
    Lang
  >;

type CollectionsPageDocumentDataSlicesSlice =
  | CollectionsSectionSlice
  | HeroSectionSlice;

/**
 * Content for Collections Page documents
 */
interface CollectionsPageDocumentData {
  /**
   * Slice Zone field in *Collections Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: collections_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CollectionsPageDocumentDataSlicesSlice> /**
   * Meta Title field in *Collections Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: collections_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Collections Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: collections_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Collections Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: collections_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Collections Page document from Prismic
 *
 * - **API ID**: `collections_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CollectionsPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CollectionsPageDocumentData>,
    "collections_page",
    Lang
  >;

type ContactPageDocumentDataSlicesSlice =
  | ContactFormSectionSlice
  | HeroSectionSlice;

/**
 * Content for Contact Page documents
 */
interface ContactPageDocumentData {
  /**
   * Slice Zone field in *Contact Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactPageDocumentDataSlicesSlice> /**
   * Meta Title field in *Contact Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contact_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Contact Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contact Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Contact Page document from Prismic
 *
 * - **API ID**: `contact_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactPageDocumentData>,
    "contact_page",
    Lang
  >;

type CustomizePageDocumentDataSlicesSlice =
  | HeroSectionSlice
  | CustomizeFormSectionSlice;

/**
 * Content for Customize Page documents
 */
interface CustomizePageDocumentData {
  /**
   * Slice Zone field in *Customize Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: customize_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CustomizePageDocumentDataSlicesSlice> /**
   * Meta Title field in *Customize Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: customize_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Customize Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: customize_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Customize Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: customize_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Customize Page document from Prismic
 *
 * - **API ID**: `customize_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CustomizePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CustomizePageDocumentData>,
    "customize_page",
    Lang
  >;

type HomePageDocumentDataSlicesSlice =
  | BlogsSectionSlice
  | InstagramSectionSlice
  | CtaSectionSlice
  | CollectionsSectionSlice
  | FeaturedProductsSectionSlice
  | FeaturesSectionSlice
  | CategoriesSectionSlice
  | HeroSectionSlice;

/**
 * Content for Home Page documents
 */
interface HomePageDocumentData {
  /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice> /**
   * Meta Title field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Meta Title [40-65 chars]
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page Description [70-155 chars]
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Featured Image field in *Home Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.featured_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<"large" | "medium" | "thumbnail">;
}

/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

/**
 * Item in *Product Page → Items*
 */
export interface ProductPageDocumentDataItemsItem {
  /**
   * Image field in *Product Page → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product_page.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

type ProductPageDocumentDataSlicesSlice = never;

/**
 * Content for Product Page documents
 */
interface ProductPageDocumentData {
  /**
   * Items field in *Product Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: product_page.items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<ProductPageDocumentDataItemsItem>>;

  /**
   * Title field in *Product Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Title
   * - **API ID Path**: product_page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Old Price field in *Product Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_page.old_price
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  old_price: prismic.KeyTextField;

  /**
   * New Price field in *Product Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_page.new_price
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  new_price: prismic.KeyTextField;

  /**
   * Description field in *Product Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description
   * - **API ID Path**: product_page.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Slice Zone field in *Product Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: product_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProductPageDocumentDataSlicesSlice> /**
   * Meta Title field in *Product Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: product_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Product Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: product_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Product Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Product Page document from Prismic
 *
 * - **API ID**: `product_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProductPageDocumentData>,
    "product_page",
    Lang
  >;

export type AllDocumentTypes =
  | AboutPageDocument
  | BlogPostDocument
  | BlogsPageDocument
  | CategoriesPageDocument
  | CollectionsPageDocument
  | ContactPageDocument
  | CustomizePageDocument
  | HomePageDocument
  | ProductPageDocument;

/**
 * Item in *AboutSection → Default → Primary → Items*
 */
export interface AboutSectionSliceDefaultPrimaryItemsItem {
  /**
   * Title field in *AboutSection → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Title
   * - **API ID Path**: about_section.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *AboutSection → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description
   * - **API ID Path**: about_section.default.primary.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *AboutSection → Default → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *AboutSection → Default → Primary*
 */
export interface AboutSectionSliceDefaultPrimary {
  /**
   * Heading field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Heading
   * - **API ID Path**: about_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Sub Heading field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Sub Heading
   * - **API ID Path**: about_section.default.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading: prismic.RichTextField;

  /**
   * Items field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<AboutSectionSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for AboutSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutSection*
 */
type AboutSectionSliceVariation = AboutSectionSliceDefault;

/**
 * AboutSection Shared Slice
 *
 * - **API ID**: `about_section`
 * - **Description**: AboutSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSectionSlice = prismic.SharedSlice<
  "about_section",
  AboutSectionSliceVariation
>;

/**
 * Primary content in *BlogDetailsSection → Default → Primary*
 */
export interface BlogDetailsSectionSliceDefaultPrimary {
  /**
   * Details field in *BlogDetailsSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Details
   * - **API ID Path**: blog_details_section.default.primary.details
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  details: prismic.RichTextField;

  /**
   * Image field in *BlogDetailsSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_details_section.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for BlogDetailsSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogDetailsSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogDetailsSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogDetailsSection*
 */
type BlogDetailsSectionSliceVariation = BlogDetailsSectionSliceDefault;

/**
 * BlogDetailsSection Shared Slice
 *
 * - **API ID**: `blog_details_section`
 * - **Description**: BlogDetailsSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogDetailsSectionSlice = prismic.SharedSlice<
  "blog_details_section",
  BlogDetailsSectionSliceVariation
>;

/**
 * Primary content in *BlogsSection → Default → Primary*
 */
export interface BlogsSectionSliceDefaultPrimary {
  /**
   * Heading field in *BlogsSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogs_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Sub Heading field in *BlogsSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogs_section.default.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_heading: prismic.KeyTextField;

  /**
   * Number field in *BlogsSection → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: blogs_section.default.primary.number
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  number: prismic.NumberField;
}

/**
 * Default variation for BlogsSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogsSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogsSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogsSection*
 */
type BlogsSectionSliceVariation = BlogsSectionSliceDefault;

/**
 * BlogsSection Shared Slice
 *
 * - **API ID**: `blogs_section`
 * - **Description**: BlogsSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogsSectionSlice = prismic.SharedSlice<
  "blogs_section",
  BlogsSectionSliceVariation
>;

/**
 * Item in *CategoriesSection → Default → Primary → Items*
 */
export interface CategoriesSectionSliceDefaultPrimaryItemsItem {
  /**
   * Image field in *CategoriesSection → Default → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: categories_section.default.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * link field in *CategoriesSection → Default → Primary → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: categories_section.default.primary.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *CategoriesSection → Default → Primary*
 */
export interface CategoriesSectionSliceDefaultPrimary {
  /**
   * Heading field in *CategoriesSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Heading
   * - **API ID Path**: categories_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Sub Heading field in *CategoriesSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Sub Heading
   * - **API ID Path**: categories_section.default.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading: prismic.RichTextField;

  /**
   * Items field in *CategoriesSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: categories_section.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<
    Simplify<CategoriesSectionSliceDefaultPrimaryItemsItem>
  >;

  /**
   * Video field in *CategoriesSection → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: categories_section.default.primary.video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkToMediaField;

  /**
   * Link field in *CategoriesSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: categories_section.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for CategoriesSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CategoriesSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CategoriesSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CategoriesSection*
 */
type CategoriesSectionSliceVariation = CategoriesSectionSliceDefault;

/**
 * CategoriesSection Shared Slice
 *
 * - **API ID**: `categories_section`
 * - **Description**: CategoriesSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CategoriesSectionSlice = prismic.SharedSlice<
  "categories_section",
  CategoriesSectionSliceVariation
>;

/**
 * Item in *CollectionsSection → Default → Primary → Items*
 */
export interface CollectionsSectionSliceDefaultPrimaryItemsItem {
  /**
   * Image field in *CollectionsSection → Default → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: collections_section.default.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Button Link field in *CollectionsSection → Default → Primary → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: collections_section.default.primary.items[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Button Label field in *CollectionsSection → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: collections_section.default.primary.items[].button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;
}

/**
 * Primary content in *CollectionsSection → Default → Primary*
 */
export interface CollectionsSectionSliceDefaultPrimary {
  /**
   * Heading field in *CollectionsSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Heading
   * - **API ID Path**: collections_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Sub Heading field in *CollectionsSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Sub Heading
   * - **API ID Path**: collections_section.default.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading: prismic.RichTextField;

  /**
   * Items field in *CollectionsSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: collections_section.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<
    Simplify<CollectionsSectionSliceDefaultPrimaryItemsItem>
  >;
}

/**
 * Default variation for CollectionsSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CollectionsSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CollectionsSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CollectionsSection*
 */
type CollectionsSectionSliceVariation = CollectionsSectionSliceDefault;

/**
 * CollectionsSection Shared Slice
 *
 * - **API ID**: `collections_section`
 * - **Description**: CollectionsSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CollectionsSectionSlice = prismic.SharedSlice<
  "collections_section",
  CollectionsSectionSliceVariation
>;

/**
 * Primary content in *ContactFormSection → Default → Primary*
 */
export interface ContactFormSectionSliceDefaultPrimary {
  /**
   * Sub Heading field in *ContactFormSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_section.default.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_heading: prismic.KeyTextField;

  /**
   * Heading field in *ContactFormSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Heading
   * - **API ID Path**: contact_form_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *ContactFormSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description
   * - **API ID Path**: contact_form_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Address field in *ContactFormSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_section.default.primary.address
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  address: prismic.KeyTextField;

  /**
   * Phone field in *ContactFormSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_section.default.primary.phone
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone: prismic.KeyTextField;

  /**
   * Email field in *ContactFormSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_section.default.primary.email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Form Id field in *ContactFormSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_section.default.primary.form_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  form_id: prismic.KeyTextField;

  /**
   * Map Link field in *ContactFormSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_section.default.primary.map_link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  map_link: prismic.KeyTextField;
}

/**
 * Default variation for ContactFormSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactFormSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactFormSection*
 */
type ContactFormSectionSliceVariation = ContactFormSectionSliceDefault;

/**
 * ContactFormSection Shared Slice
 *
 * - **API ID**: `contact_form_section`
 * - **Description**: ContactFormSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSectionSlice = prismic.SharedSlice<
  "contact_form_section",
  ContactFormSectionSliceVariation
>;

/**
 * Primary content in *CtaSection → Default → Primary*
 */
export interface CtaSectionSliceDefaultPrimary {
  /**
   * Title field in *CtaSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Title
   * - **API ID Path**: cta_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *CtaSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description
   * - **API ID Path**: cta_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Button Label field in *CtaSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.default.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button Link field in *CtaSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Left Image field in *CtaSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.default.primary.left_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  left_image: prismic.ImageField<never>;

  /**
   * Right Image field in *CtaSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.default.primary.right_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  right_image: prismic.ImageField<never>;
}

/**
 * Default variation for CtaSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaSectionSliceDefaultPrimary>,
  never
>;

/**
 * Offer variation for CtaSection Slice
 *
 * - **API ID**: `offer`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSectionSliceOffer = prismic.SharedSliceVariation<
  "offer",
  Record<string, never>,
  never
>;

/**
 * Primary content in *CtaSection → Contact → Primary*
 */
export interface CtaSectionSliceContactPrimary {
  /**
   * Title field in *CtaSection → Contact → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Title
   * - **API ID Path**: cta_section.contact.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *CtaSection → Contact → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description
   * - **API ID Path**: cta_section.contact.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Button Label field in *CtaSection → Contact → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.contact.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button Link field in *CtaSection → Contact → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.contact.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Contact variation for CtaSection Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSectionSliceContact = prismic.SharedSliceVariation<
  "contact",
  Simplify<CtaSectionSliceContactPrimary>,
  never
>;

/**
 * Primary content in *CtaSection → Blog → Primary*
 */
export interface CtaSectionSliceBlogPrimary {
  /**
   * Title field in *CtaSection → Blog → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Title
   * - **API ID Path**: cta_section.blog.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *CtaSection → Blog → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description
   * - **API ID Path**: cta_section.blog.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Button Label field in *CtaSection → Blog → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.blog.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button Link field in *CtaSection → Blog → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.blog.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Blog variation for CtaSection Slice
 *
 * - **API ID**: `blog`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSectionSliceBlog = prismic.SharedSliceVariation<
  "blog",
  Simplify<CtaSectionSliceBlogPrimary>,
  never
>;

/**
 * Slice variation for *CtaSection*
 */
type CtaSectionSliceVariation =
  | CtaSectionSliceDefault
  | CtaSectionSliceOffer
  | CtaSectionSliceContact
  | CtaSectionSliceBlog;

/**
 * CtaSection Shared Slice
 *
 * - **API ID**: `cta_section`
 * - **Description**: CtaSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSectionSlice = prismic.SharedSlice<
  "cta_section",
  CtaSectionSliceVariation
>;

/**
 * Primary content in *CustomizeFormSection → Default → Primary*
 */
export interface CustomizeFormSectionSliceDefaultPrimary {
  /**
   * Form Id field in *CustomizeFormSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: customize_form_section.default.primary.form_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  form_id: prismic.KeyTextField;

  /**
   * Image field in *CustomizeFormSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: customize_form_section.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for CustomizeFormSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CustomizeFormSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CustomizeFormSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CustomizeFormSection*
 */
type CustomizeFormSectionSliceVariation = CustomizeFormSectionSliceDefault;

/**
 * CustomizeFormSection Shared Slice
 *
 * - **API ID**: `customize_form_section`
 * - **Description**: CustomizeFormSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CustomizeFormSectionSlice = prismic.SharedSlice<
  "customize_form_section",
  CustomizeFormSectionSliceVariation
>;

/**
 * Item in *FeaturedProductsSection → Default → Primary → Items*
 */
export interface FeaturedProductsSectionSliceDefaultPrimaryItemsItem {
  /**
   * image field in *FeaturedProductsSection → Default → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_products_section.default.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Link field in *FeaturedProductsSection → Default → Primary → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_products_section.default.primary.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *FeaturedProductsSection → Default → Primary*
 */
export interface FeaturedProductsSectionSliceDefaultPrimary {
  /**
   * Heading field in *FeaturedProductsSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Heading
   * - **API ID Path**: featured_products_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Sub Heading field in *FeaturedProductsSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Sub Heading
   * - **API ID Path**: featured_products_section.default.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading: prismic.RichTextField;

  /**
   * Items field in *FeaturedProductsSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_products_section.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<
    Simplify<FeaturedProductsSectionSliceDefaultPrimaryItemsItem>
  >;
}

/**
 * Default variation for FeaturedProductsSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedProductsSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedProductsSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeaturedProductsSection*
 */
type FeaturedProductsSectionSliceVariation =
  FeaturedProductsSectionSliceDefault;

/**
 * FeaturedProductsSection Shared Slice
 *
 * - **API ID**: `featured_products_section`
 * - **Description**: FeaturedProductsSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedProductsSectionSlice = prismic.SharedSlice<
  "featured_products_section",
  FeaturedProductsSectionSliceVariation
>;

/**
 * Item in *FeaturesSection → Default → Primary → Items*
 */
export interface FeaturesSectionSliceDefaultPrimaryItemsItem {
  /**
   * Icon field in *FeaturesSection → Default → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: features_section.default.primary.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *FeaturesSection → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features_section.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *FeaturesSection → Default → Primary*
 */
export interface FeaturesSectionSliceDefaultPrimary {
  /**
   * Items field in *FeaturesSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: features_section.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<
    Simplify<FeaturesSectionSliceDefaultPrimaryItemsItem>
  >;
}

/**
 * Default variation for FeaturesSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturesSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeaturesSection*
 */
type FeaturesSectionSliceVariation = FeaturesSectionSliceDefault;

/**
 * FeaturesSection Shared Slice
 *
 * - **API ID**: `features_section`
 * - **Description**: FeaturesSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesSectionSlice = prismic.SharedSlice<
  "features_section",
  FeaturesSectionSliceVariation
>;

/**
 * Item in *HeroSection → Default → Primary → Items*
 */
export interface HeroSectionSliceDefaultPrimaryItemsItem {
  /**
   * Image field in *HeroSection → Default → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Sub Heading field in *HeroSection → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.items[].sub_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_heading: prismic.KeyTextField;

  /**
   * Heading field in *HeroSection → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Heading
   * - **API ID Path**: hero_section.default.primary.items[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *HeroSection → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description
   * - **API ID Path**: hero_section.default.primary.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Button Label field in *HeroSection → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Button Label
   * - **API ID Path**: hero_section.default.primary.items[].button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button Link field in *HeroSection → Default → Primary → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.items[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Primary content in *HeroSection → Default → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * Items field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<HeroSectionSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *HeroSection → Secondary → Primary*
 */
export interface HeroSectionSliceSecondaryPrimary {
  /**
   * Image field in *HeroSection → Secondary → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.secondary.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Heading field in *HeroSection → Secondary → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Heading
   * - **API ID Path**: hero_section.secondary.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *HeroSection → Secondary → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description
   * - **API ID Path**: hero_section.secondary.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Secondary variation for HeroSection Slice
 *
 * - **API ID**: `secondary`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSliceSecondary = prismic.SharedSliceVariation<
  "secondary",
  Simplify<HeroSectionSliceSecondaryPrimary>,
  never
>;

/**
 * Primary content in *HeroSection → Blog → Primary*
 */
export interface HeroSectionSliceBlogPrimary {
  /**
   * Published Date field in *HeroSection → Blog → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.blog.primary.published_date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  published_date: prismic.DateField;

  /**
   * Heading field in *HeroSection → Blog → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Heading
   * - **API ID Path**: hero_section.blog.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Author field in *HeroSection → Blog → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.blog.primary.author
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;

  /**
   * Description field in *HeroSection → Blog → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description
   * - **API ID Path**: hero_section.blog.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *HeroSection → Blog → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.blog.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Blog variation for HeroSection Slice
 *
 * - **API ID**: `blog`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSliceBlog = prismic.SharedSliceVariation<
  "blog",
  Simplify<HeroSectionSliceBlogPrimary>,
  never
>;

/**
 * Slice variation for *HeroSection*
 */
type HeroSectionSliceVariation =
  | HeroSectionSliceDefault
  | HeroSectionSliceSecondary
  | HeroSectionSliceBlog;

/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: HeroSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

/**
 * Primary content in *InstagramSection → Default → Primary*
 */
export interface InstagramSectionSliceDefaultPrimary {
  /**
   * Woxo Id field in *InstagramSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: instagram_section.default.primary.woxo_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  woxo_id: prismic.KeyTextField;
}

/**
 * Default variation for InstagramSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InstagramSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<InstagramSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *InstagramSection*
 */
type InstagramSectionSliceVariation = InstagramSectionSliceDefault;

/**
 * InstagramSection Shared Slice
 *
 * - **API ID**: `instagram_section`
 * - **Description**: InstagramSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InstagramSectionSlice = prismic.SharedSlice<
  "instagram_section",
  InstagramSectionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutPageDocument,
      AboutPageDocumentData,
      AboutPageDocumentDataSlicesSlice,
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataSlicesSlice,
      BlogsPageDocument,
      BlogsPageDocumentData,
      BlogsPageDocumentDataSlicesSlice,
      CategoriesPageDocument,
      CategoriesPageDocumentData,
      CategoriesPageDocumentDataSlicesSlice,
      CollectionsPageDocument,
      CollectionsPageDocumentData,
      CollectionsPageDocumentDataSlicesSlice,
      ContactPageDocument,
      ContactPageDocumentData,
      ContactPageDocumentDataSlicesSlice,
      CustomizePageDocument,
      CustomizePageDocumentData,
      CustomizePageDocumentDataSlicesSlice,
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      ProductPageDocument,
      ProductPageDocumentData,
      ProductPageDocumentDataItemsItem,
      ProductPageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutSectionSlice,
      AboutSectionSliceDefaultPrimaryItemsItem,
      AboutSectionSliceDefaultPrimary,
      AboutSectionSliceVariation,
      AboutSectionSliceDefault,
      BlogDetailsSectionSlice,
      BlogDetailsSectionSliceDefaultPrimary,
      BlogDetailsSectionSliceVariation,
      BlogDetailsSectionSliceDefault,
      BlogsSectionSlice,
      BlogsSectionSliceDefaultPrimary,
      BlogsSectionSliceVariation,
      BlogsSectionSliceDefault,
      CategoriesSectionSlice,
      CategoriesSectionSliceDefaultPrimaryItemsItem,
      CategoriesSectionSliceDefaultPrimary,
      CategoriesSectionSliceVariation,
      CategoriesSectionSliceDefault,
      CollectionsSectionSlice,
      CollectionsSectionSliceDefaultPrimaryItemsItem,
      CollectionsSectionSliceDefaultPrimary,
      CollectionsSectionSliceVariation,
      CollectionsSectionSliceDefault,
      ContactFormSectionSlice,
      ContactFormSectionSliceDefaultPrimary,
      ContactFormSectionSliceVariation,
      ContactFormSectionSliceDefault,
      CtaSectionSlice,
      CtaSectionSliceDefaultPrimary,
      CtaSectionSliceContactPrimary,
      CtaSectionSliceBlogPrimary,
      CtaSectionSliceVariation,
      CtaSectionSliceDefault,
      CtaSectionSliceOffer,
      CtaSectionSliceContact,
      CtaSectionSliceBlog,
      CustomizeFormSectionSlice,
      CustomizeFormSectionSliceDefaultPrimary,
      CustomizeFormSectionSliceVariation,
      CustomizeFormSectionSliceDefault,
      FeaturedProductsSectionSlice,
      FeaturedProductsSectionSliceDefaultPrimaryItemsItem,
      FeaturedProductsSectionSliceDefaultPrimary,
      FeaturedProductsSectionSliceVariation,
      FeaturedProductsSectionSliceDefault,
      FeaturesSectionSlice,
      FeaturesSectionSliceDefaultPrimaryItemsItem,
      FeaturesSectionSliceDefaultPrimary,
      FeaturesSectionSliceVariation,
      FeaturesSectionSliceDefault,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimaryItemsItem,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceSecondaryPrimary,
      HeroSectionSliceBlogPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      HeroSectionSliceSecondary,
      HeroSectionSliceBlog,
      InstagramSectionSlice,
      InstagramSectionSliceDefaultPrimary,
      InstagramSectionSliceVariation,
      InstagramSectionSliceDefault,
    };
  }
}
