// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutPageDocumentDataSlicesSlice =
  | TeamSectionSlice
  | CtaSectionSlice
  | TabbedSectionSlice
  | CounterSectionSlice
  | AboutSectionSlice
  | HeroSectionSlice;

/**
 * Content for About Page documents
 */
interface AboutPageDocumentData {
  /**
   * Slice Zone field in *About Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutPageDocumentDataSlicesSlice> /**
   * Meta Description field in *About Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *About Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * About Page document from Prismic
 *
 * - **API ID**: `about_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AboutPageDocumentData>,
    "about_page",
    Lang
  >;

type BlogPostDocumentDataSlicesSlice =
  | HeroSectionSlice
  | CtaSectionSlice
  | DetailsSectionSlice;

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
  /**
   * Heading field in *Blog Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *Blog Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Published Date field in *Blog Post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.published_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  published_date: prismic.DateField;

  /**
   * Slice Zone field in *Blog Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice> /**
   * Meta Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Featured Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.featured_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<"large" | "medium" | "thumbnail">;
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    "blog_post",
    Lang
  >;

type BlogsPageDocumentDataSlicesSlice =
  | CtaSectionSlice
  | PaginationSectionSlice
  | BlogsSectionSlice
  | HeroSectionSlice;

/**
 * Content for Blogs Page documents
 */
interface BlogsPageDocumentData {
  /**
   * Slice Zone field in *Blogs Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blogs_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogsPageDocumentDataSlicesSlice> /**
   * Meta Description field in *Blogs Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blogs_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blogs Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogs_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Blogs Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blogs_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Blogs Page document from Prismic
 *
 * - **API ID**: `blogs_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogsPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<BlogsPageDocumentData>,
    "blogs_page",
    Lang
  >;

type ContactPageDocumentDataSlicesSlice =
  | ContactSectionSlice
  | HeroSectionSlice;

/**
 * Content for Contact Page documents
 */
interface ContactPageDocumentData {
  /**
   * Slice Zone field in *Contact Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactPageDocumentDataSlicesSlice> /**
   * Meta Description field in *Contact Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contact Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Contact Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contact_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Contact Page document from Prismic
 *
 * - **API ID**: `contact_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactPageDocumentData>,
    "contact_page",
    Lang
  >;

type FooterDocumentDataSlicesSlice = LinkItemSlice;

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Background Image field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.background_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Logo field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Description field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Facebook field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.facebook
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  facebook: prismic.LinkField;

  /**
   * Twitter field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.twitter
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  twitter: prismic.LinkField;

  /**
   * Google field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.google
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  google: prismic.LinkField;

  /**
   * Linkedin field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.linkedin
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkedin: prismic.LinkField;

  /**
   * Slice Zone field in *Footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FooterDocumentDataSlicesSlice>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type GalleryPageDocumentDataSlicesSlice =
  | HeroSectionSlice
  | GallerySectionSlice;

/**
 * Content for Gallery Page documents
 */
interface GalleryPageDocumentData {
  /**
   * Slice Zone field in *Gallery Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<GalleryPageDocumentDataSlicesSlice> /**
   * Meta Description field in *Gallery Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: gallery_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Gallery Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Gallery Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: gallery_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Gallery Page document from Prismic
 *
 * - **API ID**: `gallery_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GalleryPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<GalleryPageDocumentData>,
    "gallery_page",
    Lang
  >;

type HeaderDocumentDataSlicesSlice = NavMenuItemSlice;

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * Logo field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Button Label field in *Header*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.button_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  button_label: prismic.RichTextField;

  /**
   * Button Link field in *Header*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.button_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  button_link: prismic.RichTextField;

  /**
   * Slice Zone field in *Header*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: header.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HeaderDocumentDataSlicesSlice>;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

type HomePageDocumentDataSlicesSlice =
  | TeamSectionSlice
  | GallerySectionSlice
  | CtaSectionSlice
  | PricingSectionSlice
  | FeaturesSectionSlice
  | BrandsSectionSlice
  | CtaFormSectionSlice
  | BlogsSectionSlice
  | TestimonialSectionSlice
  | ServicesSectionSlice
  | AboutSectionSlice
  | HeroSectionSlice;

/**
 * Content for Home Page documents
 */
interface HomePageDocumentData {
  /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice> /**
   * Meta Description field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

type ServicePageDocumentDataSlicesSlice =
  | ServiceDetailSectionSlice
  | FaqSectionSlice
  | HeroSectionSlice
  | AboutSectionSlice
  | CtaSectionSlice
  | ServicesSectionSlice
  | BlogsSectionSlice
  | CounterSectionSlice
  | DetailsSectionSlice
  | TestimonialSectionSlice;

/**
 * Content for Service Page documents
 */
interface ServicePageDocumentData {
  /**
   * Heading field in *Service Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Heading
   * - **API ID Path**: service_page.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Published Date field in *Service Page*
   *
   * - **Field Type**: Date
   * - **Placeholder**: Published Date
   * - **API ID Path**: service_page.published_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  published_date: prismic.DateField;

  /**
   * Description field in *Service Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description
   * - **API ID Path**: service_page.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *Service Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_page.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Service Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: service_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ServicePageDocumentDataSlicesSlice> /**
   * Meta Title field in *Service Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Meta Title [40-65 chars]
   * - **API ID Path**: service_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Service Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page Description [70-155 chars]
   * - **API ID Path**: service_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Featured Image field in *Service Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_page.featured_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<"large" | "medium" | "thumbnail">;
}

/**
 * Service Page document from Prismic
 *
 * - **API ID**: `service_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServicePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ServicePageDocumentData>,
    "service_page",
    Lang
  >;

type ServicesPageDocumentDataSlicesSlice =
  | CtaFormSectionSlice
  | BrandsSectionSlice
  | FeaturesSectionSlice
  | PaginationSectionSlice
  | CtaSectionSlice
  | ServicesSectionSlice
  | HeroSectionSlice;

/**
 * Content for Services Page documents
 */
interface ServicesPageDocumentData {
  /**
   * Slice Zone field in *Services Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: services_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ServicesPageDocumentDataSlicesSlice> /**
   * Meta Description field in *Services Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: services_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Services Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Services Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: services_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Services Page document from Prismic
 *
 * - **API ID**: `services_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServicesPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ServicesPageDocumentData>,
    "services_page",
    Lang
  >;

/**
 * Content for Top Bar documents
 */
interface TopBarDocumentData {
  /**
   * Phone Title field in *Top Bar*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Phone Title
   * - **API ID Path**: top_bar.phone_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  phone_title: prismic.RichTextField;

  /**
   * Phone Number field in *Top Bar*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Phone Number
   * - **API ID Path**: top_bar.phone_number
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  phone_number: prismic.RichTextField;

  /**
   * Title field in *Top Bar*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Title
   * - **API ID Path**: top_bar.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Email Title field in *Top Bar*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Email Title
   * - **API ID Path**: top_bar.email_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  email_title: prismic.RichTextField;

  /**
   * Email field in *Top Bar*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Email
   * - **API ID Path**: top_bar.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  email: prismic.RichTextField;
}

/**
 * Top Bar document from Prismic
 *
 * - **API ID**: `top_bar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TopBarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TopBarDocumentData>,
    "top_bar",
    Lang
  >;

export type AllDocumentTypes =
  | AboutPageDocument
  | BlogPostDocument
  | BlogsPageDocument
  | ContactPageDocument
  | FooterDocument
  | GalleryPageDocument
  | HeaderDocument
  | HomePageDocument
  | ServicePageDocument
  | ServicesPageDocument
  | TopBarDocument;

/**
 * Primary content in *AboutSection → Default → Primary*
 */
export interface AboutSectionSliceDefaultPrimary {
  /**
   * Sub Heading field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading: prismic.RichTextField;

  /**
   * Heading field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Name field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Designation field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.designation
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  designation: prismic.RichTextField;

  /**
   * Signature field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.signature
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  signature: prismic.ImageField<never>;

  /**
   * Image field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for AboutSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSectionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *AboutSection → WhyUs → Primary*
 */
export interface AboutSectionSliceWhyUsPrimary {
  /**
   * Sub Heading field in *AboutSection → WhyUs → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.whyUs.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading: prismic.RichTextField;

  /**
   * Heading field in *AboutSection → WhyUs → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.whyUs.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *AboutSection → WhyUs → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.whyUs.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *AboutSection → Items*
 */
export interface AboutSectionSliceWhyUsItem {
  /**
   * Image field in *AboutSection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * WhyUs variation for AboutSection Slice
 *
 * - **API ID**: `whyUs`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSectionSliceWhyUs = prismic.SharedSliceVariation<
  "whyUs",
  Simplify<AboutSectionSliceWhyUsPrimary>,
  Simplify<AboutSectionSliceWhyUsItem>
>;

/**
 * Slice variation for *AboutSection*
 */
type AboutSectionSliceVariation =
  | AboutSectionSliceDefault
  | AboutSectionSliceWhyUs;

/**
 * AboutSection Shared Slice
 *
 * - **API ID**: `about_section`
 * - **Description**: AboutSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSectionSlice = prismic.SharedSlice<
  "about_section",
  AboutSectionSliceVariation
>;

/**
 * Primary content in *BlogsSection → Default → Primary*
 */
export interface BlogsSectionSliceDefaultPrimary {
  /**
   * Sub Heading field in *BlogsSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogs_section.default.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading: prismic.RichTextField;

  /**
   * Heading field in *BlogsSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogs_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Number field in *BlogsSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogs_section.default.primary.number
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  number: prismic.KeyTextField;
}

/**
 * Primary content in *BlogsSection → Items*
 */
export interface BlogsSectionSliceDefaultItem {
  /**
   * Image field in *BlogsSection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogs_section.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Published Date field in *BlogsSection → Items*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blogs_section.items[].published_date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  published_date: prismic.DateField;

  /**
   * Category field in *BlogsSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogs_section.items[].category
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  category: prismic.RichTextField;

  /**
   * Title field in *BlogsSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogs_section.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Link field in *BlogsSection → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: blogs_section.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for BlogsSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogsSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogsSectionSliceDefaultPrimary>,
  Simplify<BlogsSectionSliceDefaultItem>
>;

/**
 * Slice variation for *BlogsSection*
 */
type BlogsSectionSliceVariation = BlogsSectionSliceDefault;

/**
 * BlogsSection Shared Slice
 *
 * - **API ID**: `blogs_section`
 * - **Description**: BlogsSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogsSectionSlice = prismic.SharedSlice<
  "blogs_section",
  BlogsSectionSliceVariation
>;

/**
 * Primary content in *BrandsSection → Items*
 */
export interface BrandsSectionSliceDefaultItem {
  /**
   * Image field in *BrandsSection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: brands_section.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for BrandsSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BrandsSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<BrandsSectionSliceDefaultItem>
>;

/**
 * Slice variation for *BrandsSection*
 */
type BrandsSectionSliceVariation = BrandsSectionSliceDefault;

/**
 * BrandsSection Shared Slice
 *
 * - **API ID**: `brands_section`
 * - **Description**: BrandsSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BrandsSectionSlice = prismic.SharedSlice<
  "brands_section",
  BrandsSectionSliceVariation
>;

/**
 * Primary content in *ContactSection → Default → Primary*
 */
export interface ContactSectionSliceDefaultPrimary {
  /**
   * Sub Heading field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_section.default.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading: prismic.RichTextField;

  /**
   * Heading field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Map Link field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_section.default.primary.map_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  map_link: prismic.LinkField;
}

/**
 * Primary content in *ContactSection → Items*
 */
export interface ContactSectionSliceDefaultItem {
  /**
   * Icon field in *ContactSection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_section.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *ContactSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_section.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Details field in *ContactSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_section.items[].details
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  details: prismic.RichTextField;
}

/**
 * Default variation for ContactSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSectionSliceDefaultPrimary>,
  Simplify<ContactSectionSliceDefaultItem>
>;

/**
 * Slice variation for *ContactSection*
 */
type ContactSectionSliceVariation = ContactSectionSliceDefault;

/**
 * ContactSection Shared Slice
 *
 * - **API ID**: `contact_section`
 * - **Description**: ContactSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSectionSlice = prismic.SharedSlice<
  "contact_section",
  ContactSectionSliceVariation
>;

/**
 * Primary content in *CounterSection → Items*
 */
export interface CounterSectionSliceDefaultItem {
  /**
   * Icon field in *CounterSection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: counter_section.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *CounterSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: counter_section.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Number field in *CounterSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: counter_section.items[].number
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  number: prismic.KeyTextField;
}

/**
 * Default variation for CounterSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CounterSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<CounterSectionSliceDefaultItem>
>;

/**
 * Slice variation for *CounterSection*
 */
type CounterSectionSliceVariation = CounterSectionSliceDefault;

/**
 * CounterSection Shared Slice
 *
 * - **API ID**: `counter_section`
 * - **Description**: CounterSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CounterSectionSlice = prismic.SharedSlice<
  "counter_section",
  CounterSectionSliceVariation
>;

/**
 * Primary content in *CtaFormSection → Default → Primary*
 */
export interface CtaFormSectionSliceDefaultPrimary {
  /**
   * Heading field in *CtaFormSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_form_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Sub Heading field in *CtaFormSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_form_section.default.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading: prismic.RichTextField;

  /**
   * Button Label field in *CtaFormSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_form_section.default.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button Link field in *CtaFormSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_form_section.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Background Image field in *CtaFormSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_form_section.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Contact Info field in *CtaFormSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Contact Info
   * - **API ID Path**: cta_form_section.default.primary.contact_info
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  contact_info: prismic.RichTextField;
}

/**
 * Default variation for CtaFormSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaFormSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaFormSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CtaFormSection*
 */
type CtaFormSectionSliceVariation = CtaFormSectionSliceDefault;

/**
 * CtaFormSection Shared Slice
 *
 * - **API ID**: `cta_form_section`
 * - **Description**: CtaFormSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaFormSectionSlice = prismic.SharedSlice<
  "cta_form_section",
  CtaFormSectionSliceVariation
>;

/**
 * Primary content in *CtaSection → Default → Primary*
 */
export interface CtaSectionSliceDefaultPrimary {
  /**
   * Heading field in *CtaSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Number field in *CtaSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.default.primary.number
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  number: prismic.KeyTextField;

  /**
   * Email field in *CtaSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.default.primary.email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;
}

/**
 * Default variation for CtaSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaSectionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *CtaSection → Blog → Primary*
 */
export interface CtaSectionSliceBlogPrimary {
  /**
   * Heading field in *CtaSection → Blog → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Heading
   * - **API ID Path**: cta_section.blog.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *CtaSection → Blog → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description
   * - **API ID Path**: cta_section.blog.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Button Label field in *CtaSection → Blog → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.blog.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button Link field in *CtaSection → Blog → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.blog.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Blog variation for CtaSection Slice
 *
 * - **API ID**: `blog`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSectionSliceBlog = prismic.SharedSliceVariation<
  "blog",
  Simplify<CtaSectionSliceBlogPrimary>,
  never
>;

/**
 * Primary content in *CtaSection → Video → Primary*
 */
export interface CtaSectionSliceVideoPrimary {
  /**
   * Heading field in *CtaSection → Video → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Heading
   * - **API ID Path**: cta_section.video.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Button Link field in *CtaSection → Video → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.video.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Image field in *CtaSection → Video → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.video.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Video variation for CtaSection Slice
 *
 * - **API ID**: `video`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSectionSliceVideo = prismic.SharedSliceVariation<
  "video",
  Simplify<CtaSectionSliceVideoPrimary>,
  never
>;

/**
 * Slice variation for *CtaSection*
 */
type CtaSectionSliceVariation =
  | CtaSectionSliceDefault
  | CtaSectionSliceBlog
  | CtaSectionSliceVideo;

/**
 * CtaSection Shared Slice
 *
 * - **API ID**: `cta_section`
 * - **Description**: CtaSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSectionSlice = prismic.SharedSlice<
  "cta_section",
  CtaSectionSliceVariation
>;

/**
 * Primary content in *DetailsSection → Items*
 */
export interface DetailsSectionSliceDefaultItem {
  /**
   * Details field in *DetailsSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Details
   * - **API ID Path**: details_section.items[].details
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  details: prismic.RichTextField;

  /**
   * Image field in *DetailsSection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: details_section.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for DetailsSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DetailsSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<DetailsSectionSliceDefaultItem>
>;

/**
 * Primary content in *DetailsSection → Items*
 */
export interface DetailsSectionSliceBlogItem {
  /**
   * Details field in *DetailsSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Details
   * - **API ID Path**: details_section.items[].details
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  details: prismic.RichTextField;

  /**
   * Image field in *DetailsSection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: details_section.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Blog variation for DetailsSection Slice
 *
 * - **API ID**: `blog`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DetailsSectionSliceBlog = prismic.SharedSliceVariation<
  "blog",
  Record<string, never>,
  Simplify<DetailsSectionSliceBlogItem>
>;

/**
 * Slice variation for *DetailsSection*
 */
type DetailsSectionSliceVariation =
  | DetailsSectionSliceDefault
  | DetailsSectionSliceBlog;

/**
 * DetailsSection Shared Slice
 *
 * - **API ID**: `details_section`
 * - **Description**: DetailsSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DetailsSectionSlice = prismic.SharedSlice<
  "details_section",
  DetailsSectionSliceVariation
>;

/**
 * Primary content in *FaqSection → Default → Primary*
 */
export interface FaqSectionSliceDefaultPrimary {
  /**
   * Heading field in *FaqSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Heading
   * - **API ID Path**: faq_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Primary content in *FaqSection → Items*
 */
export interface FaqSectionSliceDefaultItem {
  /**
   * Question field in *FaqSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Question
   * - **API ID Path**: faq_section.items[].question
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  question: prismic.RichTextField;

  /**
   * Answer field in *FaqSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Answer
   * - **API ID Path**: faq_section.items[].answer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  answer: prismic.RichTextField;
}

/**
 * Default variation for FaqSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSectionSliceDefaultPrimary>,
  Simplify<FaqSectionSliceDefaultItem>
>;

/**
 * Slice variation for *FaqSection*
 */
type FaqSectionSliceVariation = FaqSectionSliceDefault;

/**
 * FaqSection Shared Slice
 *
 * - **API ID**: `faq_section`
 * - **Description**: FaqSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSectionSlice = prismic.SharedSlice<
  "faq_section",
  FaqSectionSliceVariation
>;

/**
 * Primary content in *FeaturesSection → Default → Primary*
 */
export interface FeaturesSectionSliceDefaultPrimary {
  /**
   * Sub Heading field in *FeaturesSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features_section.default.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading: prismic.RichTextField;

  /**
   * Heading field in *FeaturesSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Primary content in *FeaturesSection → Items*
 */
export interface FeaturesSectionSliceDefaultItem {
  /**
   * Title field in *FeaturesSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features_section.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Image field in *FeaturesSection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: features_section.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Description field in *FeaturesSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features_section.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for FeaturesSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturesSectionSliceDefaultPrimary>,
  Simplify<FeaturesSectionSliceDefaultItem>
>;

/**
 * Slice variation for *FeaturesSection*
 */
type FeaturesSectionSliceVariation = FeaturesSectionSliceDefault;

/**
 * FeaturesSection Shared Slice
 *
 * - **API ID**: `features_section`
 * - **Description**: FeaturesSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesSectionSlice = prismic.SharedSlice<
  "features_section",
  FeaturesSectionSliceVariation
>;

/**
 * Primary content in *GallerySection → Default → Primary*
 */
export interface GallerySectionSliceDefaultPrimary {
  /**
   * Sub Heading field in *GallerySection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_section.default.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading: prismic.RichTextField;

  /**
   * Heading field in *GallerySection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Primary content in *GallerySection → Items*
 */
export interface GallerySectionSliceDefaultItem {
  /**
   * Image field in *GallerySection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_section.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<"large">;

  /**
   * Video Id field in *GallerySection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_section.items[].video_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  video_id: prismic.KeyTextField;
}

/**
 * Default variation for GallerySection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GallerySectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GallerySectionSliceDefaultPrimary>,
  Simplify<GallerySectionSliceDefaultItem>
>;

/**
 * Slice variation for *GallerySection*
 */
type GallerySectionSliceVariation = GallerySectionSliceDefault;

/**
 * GallerySection Shared Slice
 *
 * - **API ID**: `gallery_section`
 * - **Description**: GallerySection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GallerySectionSlice = prismic.SharedSlice<
  "gallery_section",
  GallerySectionSliceVariation
>;

/**
 * Primary content in *HeroSection → Default → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * Sub Heading field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading: prismic.RichTextField;

  /**
   * Heading field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Button Label field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button Link field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Video Link field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.video_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video_link: prismic.LinkField;
}

/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *HeroSection → Secondary → Primary*
 */
export interface HeroSectionSliceSecondaryPrimary {
  /**
   * Heading field in *HeroSection → Secondary → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.secondary.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Image field in *HeroSection → Secondary → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.secondary.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Secondary variation for HeroSection Slice
 *
 * - **API ID**: `secondary`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSliceSecondary = prismic.SharedSliceVariation<
  "secondary",
  Simplify<HeroSectionSliceSecondaryPrimary>,
  never
>;

/**
 * Slice variation for *HeroSection*
 */
type HeroSectionSliceVariation =
  | HeroSectionSliceDefault
  | HeroSectionSliceSecondary;

/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: HeroSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

/**
 * Item in *LinkItem → Default → Primary → Title*
 */
export interface LinkItemSliceDefaultPrimaryTitleItem {}

/**
 * Primary content in *LinkItem → Default → Primary*
 */
export interface LinkItemSliceDefaultPrimary {
  /**
   * Title field in *LinkItem → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: link_item.default.primary.title[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  title: prismic.GroupField<Simplify<LinkItemSliceDefaultPrimaryTitleItem>>;
}

/**
 * Primary content in *LinkItem → Items*
 */
export interface LinkItemSliceDefaultItem {
  /**
   * Title field in *LinkItem → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: link_item.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Link field in *LinkItem → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: link_item.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for LinkItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LinkItemSliceDefaultPrimary>,
  Simplify<LinkItemSliceDefaultItem>
>;

/**
 * Slice variation for *LinkItem*
 */
type LinkItemSliceVariation = LinkItemSliceDefault;

/**
 * LinkItem Shared Slice
 *
 * - **API ID**: `link_item`
 * - **Description**: LinkItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkItemSlice = prismic.SharedSlice<
  "link_item",
  LinkItemSliceVariation
>;

/**
 * Primary content in *NavMenuItem → Default → Primary*
 */
export interface NavMenuItemSliceDefaultPrimary {
  /**
   * Title field in *NavMenuItem → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Title
   * - **API ID Path**: nav_menu_item.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Link field in *NavMenuItem → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link
   * - **API ID Path**: nav_menu_item.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *NavMenuItem → Items*
 */
export interface NavMenuItemSliceDefaultItem {
  /**
   * Title field in *NavMenuItem → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Title
   * - **API ID Path**: nav_menu_item.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Link field in *NavMenuItem → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link
   * - **API ID Path**: nav_menu_item.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Submenu field in *NavMenuItem → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_menu_item.items[].submenu
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  submenu: prismic.ContentRelationshipField<"submenu">;
}

/**
 * Default variation for NavMenuItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavMenuItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavMenuItemSliceDefaultPrimary>,
  Simplify<NavMenuItemSliceDefaultItem>
>;

/**
 * Slice variation for *NavMenuItem*
 */
type NavMenuItemSliceVariation = NavMenuItemSliceDefault;

/**
 * NavMenuItem Shared Slice
 *
 * - **API ID**: `nav_menu_item`
 * - **Description**: NavMenuItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavMenuItemSlice = prismic.SharedSlice<
  "nav_menu_item",
  NavMenuItemSliceVariation
>;

/**
 * Primary content in *PaginationSection → Default → Primary*
 */
export interface PaginationSectionSliceDefaultPrimary {
  /**
   * Heading field in *PaginationSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pagination_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;
}

/**
 * Default variation for PaginationSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PaginationSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PaginationSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PaginationSection*
 */
type PaginationSectionSliceVariation = PaginationSectionSliceDefault;

/**
 * PaginationSection Shared Slice
 *
 * - **API ID**: `pagination_section`
 * - **Description**: PaginationSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PaginationSectionSlice = prismic.SharedSlice<
  "pagination_section",
  PaginationSectionSliceVariation
>;

/**
 * Primary content in *PricingSection → Default → Primary*
 */
export interface PricingSectionSliceDefaultPrimary {
  /**
   * Sub Heading field in *PricingSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_section.default.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading: prismic.RichTextField;

  /**
   * Heading field in *PricingSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Primary content in *PricingSection → Items*
 */
export interface PricingSectionSliceDefaultItem {
  /**
   * Title field in *PricingSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_section.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *PricingSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_section.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Price field in *PricingSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_section.items[].price
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  price: prismic.KeyTextField;
}

/**
 * Default variation for PricingSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PricingSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PricingSectionSliceDefaultPrimary>,
  Simplify<PricingSectionSliceDefaultItem>
>;

/**
 * Slice variation for *PricingSection*
 */
type PricingSectionSliceVariation = PricingSectionSliceDefault;

/**
 * PricingSection Shared Slice
 *
 * - **API ID**: `pricing_section`
 * - **Description**: PricingSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PricingSectionSlice = prismic.SharedSlice<
  "pricing_section",
  PricingSectionSliceVariation
>;

/**
 * Primary content in *ServiceDetailSection → Default → Primary*
 */
export interface ServiceDetailSectionSliceDefaultPrimary {
  /**
   * Sub Heading field in *ServiceDetailSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_detail_section.default.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading: prismic.RichTextField;

  /**
   * Heading field in *ServiceDetailSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_detail_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *ServiceDetailSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_detail_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *ServiceDetailSection → Items*
 */
export interface ServiceDetailSectionSliceDefaultItem {
  /**
   * Image field in *ServiceDetailSection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_detail_section.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<"large">;

  /**
   * Video Id field in *ServiceDetailSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_detail_section.items[].video_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  video_id: prismic.KeyTextField;
}

/**
 * Default variation for ServiceDetailSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceDetailSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServiceDetailSectionSliceDefaultPrimary>,
  Simplify<ServiceDetailSectionSliceDefaultItem>
>;

/**
 * Slice variation for *ServiceDetailSection*
 */
type ServiceDetailSectionSliceVariation = ServiceDetailSectionSliceDefault;

/**
 * ServiceDetailSection Shared Slice
 *
 * - **API ID**: `service_detail_section`
 * - **Description**: ServiceDetailSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceDetailSectionSlice = prismic.SharedSlice<
  "service_detail_section",
  ServiceDetailSectionSliceVariation
>;

/**
 * Primary content in *ServicesSection → Default → Primary*
 */
export interface ServicesSectionSliceDefaultPrimary {
  /**
   * Heading field in *ServicesSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Sub Heading field in *ServicesSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_section.default.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading: prismic.RichTextField;
}

/**
 * Primary content in *ServicesSection → Items*
 */
export interface ServicesSectionSliceDefaultItem {
  /**
   * Title field in *ServicesSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_section.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Image field in *ServicesSection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services_section.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Link field in *ServicesSection → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: services_section.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Description field in *ServicesSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_section.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Price field in *ServicesSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_section.items[].price
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  price: prismic.KeyTextField;
}

/**
 * Default variation for ServicesSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesSectionSliceDefaultPrimary>,
  Simplify<ServicesSectionSliceDefaultItem>
>;

/**
 * Slice variation for *ServicesSection*
 */
type ServicesSectionSliceVariation = ServicesSectionSliceDefault;

/**
 * ServicesSection Shared Slice
 *
 * - **API ID**: `services_section`
 * - **Description**: ServicesSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSectionSlice = prismic.SharedSlice<
  "services_section",
  ServicesSectionSliceVariation
>;

/**
 * Primary content in *TabbedSection → Default → Primary*
 */
export interface TabbedSectionSliceDefaultPrimary {
  /**
   * Heading field in *TabbedSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tabbed_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Image field in *TabbedSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tabbed_section.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *TabbedSection → Items*
 */
export interface TabbedSectionSliceDefaultItem {
  /**
   * Title field in *TabbedSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tabbed_section.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Tab field in *TabbedSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tabbed_section.items[].tab
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tab: prismic.RichTextField;

  /**
   * Description field in *TabbedSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tabbed_section.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for TabbedSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TabbedSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TabbedSectionSliceDefaultPrimary>,
  Simplify<TabbedSectionSliceDefaultItem>
>;

/**
 * Slice variation for *TabbedSection*
 */
type TabbedSectionSliceVariation = TabbedSectionSliceDefault;

/**
 * TabbedSection Shared Slice
 *
 * - **API ID**: `tabbed_section`
 * - **Description**: TabbedSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TabbedSectionSlice = prismic.SharedSlice<
  "tabbed_section",
  TabbedSectionSliceVariation
>;

/**
 * Primary content in *TeamSection → Default → Primary*
 */
export interface TeamSectionSliceDefaultPrimary {
  /**
   * Sub Heading field in *TeamSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_section.default.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading: prismic.RichTextField;

  /**
   * Heading field in *TeamSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Primary content in *TeamSection → Items*
 */
export interface TeamSectionSliceDefaultItem {
  /**
   * Image field in *TeamSection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team_section.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Name field in *TeamSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_section.items[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Designation field in *TeamSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_section.items[].designation
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  designation: prismic.KeyTextField;

  /**
   * Description field in *TeamSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_section.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Link field in *TeamSection → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: team_section.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for TeamSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamSectionSliceDefaultPrimary>,
  Simplify<TeamSectionSliceDefaultItem>
>;

/**
 * Slice variation for *TeamSection*
 */
type TeamSectionSliceVariation = TeamSectionSliceDefault;

/**
 * TeamSection Shared Slice
 *
 * - **API ID**: `team_section`
 * - **Description**: TeamSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSectionSlice = prismic.SharedSlice<
  "team_section",
  TeamSectionSliceVariation
>;

/**
 * Primary content in *TestimonialSection → Default → Primary*
 */
export interface TestimonialSectionSliceDefaultPrimary {
  /**
   * Sub Heading field in *TestimonialSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_section.default.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading: prismic.RichTextField;

  /**
   * Heading field in *TestimonialSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Background Image field in *TestimonialSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_section.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Primary content in *TestimonialSection → Items*
 */
export interface TestimonialSectionSliceDefaultItem {
  /**
   * Image field in *TestimonialSection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_section.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Name field in *TestimonialSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_section.items[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Description field in *TestimonialSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_section.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for TestimonialSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialSectionSliceDefaultPrimary>,
  Simplify<TestimonialSectionSliceDefaultItem>
>;

/**
 * Slice variation for *TestimonialSection*
 */
type TestimonialSectionSliceVariation = TestimonialSectionSliceDefault;

/**
 * TestimonialSection Shared Slice
 *
 * - **API ID**: `testimonial_section`
 * - **Description**: TestimonialSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialSectionSlice = prismic.SharedSlice<
  "testimonial_section",
  TestimonialSectionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutPageDocument,
      AboutPageDocumentData,
      AboutPageDocumentDataSlicesSlice,
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataSlicesSlice,
      BlogsPageDocument,
      BlogsPageDocumentData,
      BlogsPageDocumentDataSlicesSlice,
      ContactPageDocument,
      ContactPageDocumentData,
      ContactPageDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSlicesSlice,
      GalleryPageDocument,
      GalleryPageDocumentData,
      GalleryPageDocumentDataSlicesSlice,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataSlicesSlice,
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      ServicePageDocument,
      ServicePageDocumentData,
      ServicePageDocumentDataSlicesSlice,
      ServicesPageDocument,
      ServicesPageDocumentData,
      ServicesPageDocumentDataSlicesSlice,
      TopBarDocument,
      TopBarDocumentData,
      AllDocumentTypes,
      AboutSectionSlice,
      AboutSectionSliceDefaultPrimary,
      AboutSectionSliceWhyUsPrimary,
      AboutSectionSliceWhyUsItem,
      AboutSectionSliceVariation,
      AboutSectionSliceDefault,
      AboutSectionSliceWhyUs,
      BlogsSectionSlice,
      BlogsSectionSliceDefaultPrimary,
      BlogsSectionSliceDefaultItem,
      BlogsSectionSliceVariation,
      BlogsSectionSliceDefault,
      BrandsSectionSlice,
      BrandsSectionSliceDefaultItem,
      BrandsSectionSliceVariation,
      BrandsSectionSliceDefault,
      ContactSectionSlice,
      ContactSectionSliceDefaultPrimary,
      ContactSectionSliceDefaultItem,
      ContactSectionSliceVariation,
      ContactSectionSliceDefault,
      CounterSectionSlice,
      CounterSectionSliceDefaultItem,
      CounterSectionSliceVariation,
      CounterSectionSliceDefault,
      CtaFormSectionSlice,
      CtaFormSectionSliceDefaultPrimary,
      CtaFormSectionSliceVariation,
      CtaFormSectionSliceDefault,
      CtaSectionSlice,
      CtaSectionSliceDefaultPrimary,
      CtaSectionSliceBlogPrimary,
      CtaSectionSliceVideoPrimary,
      CtaSectionSliceVariation,
      CtaSectionSliceDefault,
      CtaSectionSliceBlog,
      CtaSectionSliceVideo,
      DetailsSectionSlice,
      DetailsSectionSliceDefaultItem,
      DetailsSectionSliceBlogItem,
      DetailsSectionSliceVariation,
      DetailsSectionSliceDefault,
      DetailsSectionSliceBlog,
      FaqSectionSlice,
      FaqSectionSliceDefaultPrimary,
      FaqSectionSliceDefaultItem,
      FaqSectionSliceVariation,
      FaqSectionSliceDefault,
      FeaturesSectionSlice,
      FeaturesSectionSliceDefaultPrimary,
      FeaturesSectionSliceDefaultItem,
      FeaturesSectionSliceVariation,
      FeaturesSectionSliceDefault,
      GallerySectionSlice,
      GallerySectionSliceDefaultPrimary,
      GallerySectionSliceDefaultItem,
      GallerySectionSliceVariation,
      GallerySectionSliceDefault,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceSecondaryPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      HeroSectionSliceSecondary,
      LinkItemSlice,
      LinkItemSliceDefaultPrimaryTitleItem,
      LinkItemSliceDefaultPrimary,
      LinkItemSliceDefaultItem,
      LinkItemSliceVariation,
      LinkItemSliceDefault,
      NavMenuItemSlice,
      NavMenuItemSliceDefaultPrimary,
      NavMenuItemSliceDefaultItem,
      NavMenuItemSliceVariation,
      NavMenuItemSliceDefault,
      PaginationSectionSlice,
      PaginationSectionSliceDefaultPrimary,
      PaginationSectionSliceVariation,
      PaginationSectionSliceDefault,
      PricingSectionSlice,
      PricingSectionSliceDefaultPrimary,
      PricingSectionSliceDefaultItem,
      PricingSectionSliceVariation,
      PricingSectionSliceDefault,
      ServiceDetailSectionSlice,
      ServiceDetailSectionSliceDefaultPrimary,
      ServiceDetailSectionSliceDefaultItem,
      ServiceDetailSectionSliceVariation,
      ServiceDetailSectionSliceDefault,
      ServicesSectionSlice,
      ServicesSectionSliceDefaultPrimary,
      ServicesSectionSliceDefaultItem,
      ServicesSectionSliceVariation,
      ServicesSectionSliceDefault,
      TabbedSectionSlice,
      TabbedSectionSliceDefaultPrimary,
      TabbedSectionSliceDefaultItem,
      TabbedSectionSliceVariation,
      TabbedSectionSliceDefault,
      TeamSectionSlice,
      TeamSectionSliceDefaultPrimary,
      TeamSectionSliceDefaultItem,
      TeamSectionSliceVariation,
      TeamSectionSliceDefault,
      TestimonialSectionSlice,
      TestimonialSectionSliceDefaultPrimary,
      TestimonialSectionSliceDefaultItem,
      TestimonialSectionSliceVariation,
      TestimonialSectionSliceDefault,
    };
  }
}
