// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_section: dynamic(() => import("./AboutSection")),
  blog_details_section: dynamic(() => import("./BlogDetailsSection")),
  blogs_section: dynamic(() => import("./BlogsSection")),
  categories_section: dynamic(() => import("./CategoriesSection")),
  collections_section: dynamic(() => import("./CollectionsSection")),
  contact_form_section: dynamic(() => import("./ContactFormSection")),
  cta_section: dynamic(() => import("./CtaSection")),
  customize_form_section: dynamic(() => import("./CustomizeFormSection")),
  faq_section: dynamic(() => import("./FaqSection")),
  featured_products_section: dynamic(() => import("./FeaturedProductsSection")),
  features_section: dynamic(() => import("./FeaturesSection")),
  hero_section: dynamic(() => import("./HeroSection")),
  instagram_section: dynamic(() => import("./InstagramSection")),
  policy_section: dynamic(() => import("./PolicySection")),
};
