// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_section: dynamic(() => import("./AboutSection")),
  blogs_section: dynamic(() => import("./BlogsSection")),
  brands_section: dynamic(() => import("./BrandsSection")),
  contact_section: dynamic(() => import("./ContactSection")),
  cta_form_section: dynamic(() => import("./CtaFormSection")),
  cta_section: dynamic(() => import("./CtaSection")),
  details_section: dynamic(() => import("./DetailsSection")),
  // faq_section: dynamic(() => import("./FaqSection")),
  features_section: dynamic(() => import("./FeaturesSection")),
  gallery_section: dynamic(() => import("./GallerySection")),
  hero_section: dynamic(() => import("./HeroSection")),
  link_item: dynamic(() => import("./LinkItem")),
  nav_menu_item: dynamic(() => import("./NavMenuItem")),
  // pagination_section: dynamic(() => import("./PaginationSection")),
  pricing_section: dynamic(() => import("./PricingSection")),
  service_detail_section: dynamic(() => import("./ServiceDetailSection")),
  services_section: dynamic(() => import("./ServicesSection")),
  // tabbed_section: dynamic(() => import("./TabbedSection")),
  team_section: dynamic(() => import("./TeamSection")),
  testimonial_section: dynamic(() => import("./TestimonialSection")),
};
